import { expect, test } from 'bun:test';
import { renderToStaticMarkup } from 'react-dom/server';
import { MemoryRouter } from 'react-router';
import Article, { DATE_PUBLISHED, DATE_MODIFIED, DESCRIPTION } from '../app/articles/content/community/weekly-deep-dive-into-ai-and-ml-advancements-updates';
import { ARTICLE_REGISTRY } from '../app/articles/registry';
test('classification issue separates examples, pretraining, accuracy and explanation evidence', () => {
 const html = renderToStaticMarkup(<MemoryRouter><Article /></MemoryRouter>);
 const entry = ARTICLE_REGISTRY['community/weekly-deep-dive-into-ai-and-ml-advancements-updates'];
 expect(entry.date).toBe(DATE_PUBLISHED);
 expect(entry.dateModified).toBe(DATE_MODIFIED);
 expect(entry.description).toBe(DESCRIPTION);
 expect(entry.authors).toHaveLength(4);
 for (const text of ['2510.06931v1', '93% average accuracy', 'not an MLAI replication', 'Fictional arithmetic', '95% accuracy', 'recall is 0%', 'zero denominator', 'Classification result reading record']) expect(html).toContain(text);
 expect(html).toContain('data-article-icp="COMMUNITY"');
 expect(html).toContain('href="/events"');
 expect(html).not.toContain('Three questions people are hammering');
 expect(html).not.toContain('paper you should pretend');
 expect(950 / 1000).toBe(0.95);
 expect(0 / 50).toBe(0);
});
