
    // Test article generated by Content Factory Agent Verification
    export default function Page() {
      return (
        <main className="container mx-auto p-4">
          <h1 className="text-4xl font-bold mb-4">Test Article 183043</h1>
          <p>This is a test deployment to verify Cloudflare Preview URL extraction.</p>
        </main>
      )
    }
    